#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/web/wp/wp-load.php';

use Symfony\Component\Console\Application;

$app = new Application();

foreach ( app( BROCOOLY_CONSOLE_COMMANDS_KEY ) as $command ) {
    $commandObject = new $command();

    if ( isProduction() && $commandObject->notAllowedInProduction() ) {
        continue;
    }

	$app->add( $commandObject );
}

$app->run();